# This is a basic workflow to help you get started with Actions

name: debugWithPetsc

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events
  push:

  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  COMPILE_JOBS: 12

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: install petsc
        run: |
          sudo apt-get -y update --fix-missing
          sudo apt-get -y install petsc-dev

      # Runs a set of commands using the runners shell
      - name: Run CMake, build and test
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Debug \
            -DENABLE_TESTING=1 -DUPDATE_SUBMODULES=1 \
            -DENABLE_PETSC=1 -DENABLE_MPI=1 \
            -DPETSC_DIR=/usr/lib/petscdir/petsc3.22/ -DPETSC_ARCH=x86_64-linux-gnu-real \
            ..
          make feNG -j$COMPILE_JOBS
          
      
