# Build the library without any dependency
name: debug

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events
  push:

  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  COMPILE_JOBS: 12

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run CMake, build and test
        run: |
          cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTING=1 -DUPDATE_SUBMODULES=1 $GITHUB_WORKSPACE
          make feNG -j$COMPILE_JOBS
          ctest --output-on-failure
